### ISSUE TITLE
Generieker maken 

### ISSUE THREAD

**Issue by nicolasschaus** [nicolasschaus/WAD-Opdracht#11]
Dag Simon,

Ik snap de opmerking om de code generieker te maken en wat je hiermee bedoeld! Maar het lukt mij niet om het resultaat te bekomen... Ik heb mijn match model aangepast naar één enkele match en een poule model gemaakt waar 3 arrays in moeten komen met elk een match. Op een of andere manier lukt dit niet en ik zie geen andere manier om dit te doen. Ik heb er echt al heel lang op gezocht en ondertussen een heel stuk van de code gewijzigd, daarmee dat ik ze nog niet push... Ik zet hieronder wel even de models en code!

match model:
class Match {
  constructor(land1, score1, land2, score2) {
    this.id = uniqid();

    this.land1 = land1;
    this.land2 = land2;

    this.score1 = score1;
    this.score2 = score2;
  }
}

poule model:
class Poule {
  constructor(match1, match2, match3) {
    this.id = uniqid();
    this.match1 = [];
    this.match2 = [];
    this.match3 = [];
  }
}

store: 
class Store {
  matches=[];
  poule=[];

  constructor() {

    this.addToPoule([new Match(`België`, 0, `belgie`, 0)], [new Match(`België`, 0, `Engeland`, 0)], [new Match(`België`, 0, `Engeland`, 0)]);
  }

  addMatch = match => {
   this.matches.push(match);

  }

    addToPoule = poule => {
     this.poule.push(poule);

    }

Moest je mij op weg kunnen zetten zou ik het erg waarderen want momenteel kan ik niet verder...

Vriendelijke groeten,
Nicolas

**Comment by SimonVanherweghe** [comment]
Start mss met 1 poule bij te houden in de store, dat zal het makkelijker maken in het begin.

In de store heb je dan enkel 1 property 'poule' nodig.
In de poule model plaats je een matches array (niet in de store) en maak je die op zich observable etc... De addMatch method zit dan ook in de poule model.
Je moet niet 'alles' vanuit de store regelen, je mag gerust de mogelijkheden van van de models gebruiken die in de store zitten.
